export const CORP_ARCHETYPES = {
  AgInfusion: [
    ["Sisyphus Protocol", "Sisyphus Ag"],
    ["Punitive Counterstrike", "Punitive Ag"],
    ["Nisei MK II", "Reg Ag"],
  ],
  Outfit: [
    ["Big Deal", "FA Outfit"],
    ["Arella Salvatore", "FA Outfit"],
    ["Biotic Labor", "FA Outfit"],
    ["Punitive Counterstrike", "Punitive Outfit"],
    ["End of the Line", "Tag and Bag Outfit"],
    ["Broad Daylight", "Punch Outfit"],
    "Other Outfit",
  ],
  PD: [
    ["Midnight-3 Arcology", "Shoot the Moon PD"],
    ["Anoetic Void", "Skunkvoid PD"],
    ["Salvo Testing", "Core PD"],
    ["Jinja City Grid", "Jinja PD"],
  ],
  PE: [
    ["See How They Run", "End of the Line", "Neurospike", "SHTR PE"],
    ["Punitive Counterstrike", "Punitive PE"],
    ["Prāna Condenser", "Moon Pool", "Loud PE"],
    ["assets>20", "Assets PE"],
    "Other PE",
  ],
  Ampère: "Reg Ampère",
  Thule: [
    ["End of the Line", "Barf Thule"],
    ["Cohort Guidance Program", "Cohort Thule"],
  ],
  MirrorMorph: [
    ["Salvo Testing", "Core MirrorMorph"],
    ["Cold Site Server", "IcyHot MirrorMorph"],
  ],
  Saraswati: [["Punitive Counterstrike", "Punitive Saraswati"]],
  GameNET: "GameNET",
  Asa: [
    ["Punitive Counterstrike", "Punitive Asa"],
    ["Salvo Testing", "Core Asa"],
    ["Amani Senai", "Amani Asa"],
    ["MCA Austerity Policy", "Jukebox Asa"],
    ["The Holo Man", "Holo Asa"],
    ["Cohort Guidance Program", "Cohort Asa"],
    ["Anoetic Void", "Skunkvoid Asa"],
  ],
  Sportsmetal: [
    ["End of the Line", "Barf Sports"],
    ["Moon Pool", "Ontological Dependence", "Mooncore Sports"],
    ["Arella Salvatore", "Arella Sports"],
    ["Amani Senai", "Amani Sports"],
    "Other Sports",
  ],
  Azmari: [
    ["Better Citizen Program", "BCP Azmari"],
    ["Neurospike", "Punitive Counterstrike", "EAzmari"],
    ["End of the Line", "Tag and Bag Azmari"],
    ["AR-Enhanced Security", "ARES Azmari"],
    "Other Azmari",
  ],
  BtL: [
    ["Biotic Labor", "FA BtL"],
    ["Public Trail", "End of the Line", "Built to Blast BtL"],
    ["Wall to Wall", "Sokka BtL"],
    ["Eminent Domain", "Archer", "Tucana", "Emdom BtL"],
    ["Vladisibirsk City Grid", "Vlad BtL"],
  ],
  Issuaq: [
    ["Punitive Counterstrike", "Punitive Issuaq"],
    ["Cerebral Overwriter", "Traps Issuaq"],
    "Other Issuaq",
  ],
  RH: [
    ["Punitive Counterstrike", "Punitive RH"],
    ["Sisyphus Protocol", "Sisyphus RH"],
    "Other RH",
  ],
  NEH: [
    ["End of the Line", "Kill NEH"],
    ["AR-Enhanced Security", "ARES NEH"],
    ["Artificial Cryptocrash", "Cryptocash NEH"],
  ],
  Pravdivost: [
    ["AR-Enhanced Security", "Assets Pravdivost"],
    ["Vladisibirsk City Grid", "Vlad Pravdivost"],
  ],
  Thunderbolt: "Thunderbolt",
  Jemison: [["End of the Line", "Tag and Bag Jemison"], "Reg Jemison"],
  Nuvem: [
    ["Punitive Counterstrike", "Punitive Nuvem"],
    ["End of the Line", "Tag and Bag Nuvem"],
    "Other Nuvem",
  ],
  "A Teia": [
    ["Jinja City Grid", "Flower Sermon", "Jinja Sermon A Teia"],
    ["Moon Pool", "Audacity", "FA A Teia"],
    ["Clearinghouse", "Clearinghouse A Teia"],
    "Other A Teia",
  ],
  Epiphany: [["Restore", "Stoke the Embers", "FA Epiphany"], "Other Epiphany"],
  Ob: [
    ["Mutually Assured Destruction", "Venti Ob"],
    ["End of the Line", "Asset Kill Ob"],
    ["Calibration Testing", "Tucana", "Calicana Ob"],
    ["ice>19", "Glacier Ob"],
    ["asset>10", "Facet Ob"],
    "Rush Ob",
  ],
  "Earth Station": "Other Earth Station",
};

export const RUNNER_ARCHETYPES = {
  Hosh: [
    ["K2CP Turbine", "Reg Hosh"],
    ["Takobi", "Reg Hosh"],
    ["Audrey v2", "Mulch Hosh"],
    ["Arruaceiras Crew", "Devil Charm", "Patchwork", "Patchwork Crew Hosh"],
    ["Arruaceiras Crew", "Devil Charm", "Aniccam", "Aniccam Crew Hosh"],
    ["Arruaceiras Crew", "Devil Charm", "Other Crew Hosh"],
    ["Buzzsaw", "Cleaver", "Echelon", "Reg Hosh"],
    ["Daeg, First Net-Cat", "Companion Hosh"],
    ["Persephone", "Persephone", "Persephone Hosh"],
  ],
  Esâ: "Reg Esâ",
  Lat: [
    ["Aesop’s Pawnshop", "LilyPAD", "Aesop's Lat"],
    ["Aniccam", "Deep Dive", "Boring Lat"],
    ["Swift", "Swift Lat"],
    "Other Lat",
  ],
  Sable: [
    ["Jeitinho", "Knife Sable"],
    ["Deep Dive", "Deep Dive Sable"],
    ["WAKE Implant v2A-JRJ", "Reg Sable"],
  ],
  Arissana: [
    ["K2CP Turbine", "Kyuban", "Urban Art Vernissage", "Turbine Ari"],
    ["Spree", "Pichação", "Botulus", "Spree Ari"],
    ["Swift", "Swift Ari"],
    ["Aesop’s Pawnshop", "Aesop's Ari"],
    "Other Ari",
  ],
  Steve: [
    ['Tsakhia "Bankhar" Gantulga', "Bankhar Steve"],
    ["Credit Kiting", "Smooth Dupes Steve"],
    "Other Steve",
  ],
  Kit: [
    ["Inversificator", "Inversificator Kit"],
    ["Lobisomem", "Orca", "Reg Kit"],
  ],
  Zahya: [
    ["Manuel Lattes de Moura", "Self-Defense Zahya"],
    ["The Twinning", "Twinning Zahya"],
  ],
  Freedom: [
    ["God of War", "Counter Surveillance", "Consume Tag Freedom"],
    ["Simulchip", "Mulch Freedom"],
    ["The Twinning", "Zombie Freedom"],
    ["Audrey v2", "Zombie Freedom"],
  ],
  Tāo: [["Hermes", "Hermes Tāo"]],
  Mercury: [
    ["Femme Fatale", "Femme Fatale Mercury"],
    ["Hermes", "Hermes Mercury"],
  ],
  Loup: [["Simulchip", "Mulch Loup"], "Other Loup"],
  Seb: [
    ["Audrey v2", "Buffer Drive", "Audrey Seb"],
    ["Buzzsaw", "Cleaver", "Reg Seb"],
    ["Arruaceiras Crew", "Devil Charm", "Crew Charm Seb"],
    "Other Seb",
  ],
  419: [
    ["Counter Surveillance", "Tagme 419"],
    ["Mining Accident", "Econ Denial 419"],
  ],
  Akiko: [
    ["Lobisomem", "Grug Akiko"],
    ["“Pretty” Mary da Silva", "Girls Akiko"],
  ],
  Ayla: [["Rosetta 2.0", "Rosetta Ayla"], "Other Ayla"],
  Reina: [["Aniccam", "Arruaceiras Crew", "Crew Charm Reina"]],
  Ken: [["Deep Dive", "Deep Dive Ken"], "Reg Ken"],
  Nova: [["K2CP Turbine", "Turbine Nova"]],
  Az: "Reg Az",
  Quetzal: "Reg Quetzal",
};

export const ALL_ARCHETYPES = {
  ...RUNNER_ARCHETYPES,
  ...CORP_ARCHETYPES,
};
