-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "decklists" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "decklists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"cards" jsonb,
	"archetype" text
);
--> statement-breakpoint
ALTER TABLE "decklists" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tournaments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tournaments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_modified_at" timestamp,
	"name" text,
	"url" text,
	"meta" text DEFAULT '' NOT NULL,
	"date" date,
	"location" text,
	"region" text,
	"format" text DEFAULT 'sss',
	"abr_url" text,
	"cardpool" text DEFAULT 'Standard'
);
--> statement-breakpoint
ALTER TABLE "tournaments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "cards" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "standings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "standings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"tournament_id" bigint NOT NULL,
	"corp_wins" bigint DEFAULT '0' NOT NULL,
	"corp_losses" bigint DEFAULT '0' NOT NULL,
	"corp_draws" bigint DEFAULT '0' NOT NULL,
	"corp_identity" text DEFAULT '' NOT NULL,
	"runner_wins" bigint DEFAULT '0' NOT NULL,
	"runner_losses" bigint DEFAULT '0' NOT NULL,
	"runner_draws" bigint DEFAULT '0' NOT NULL,
	"runner_identity" text DEFAULT '' NOT NULL,
	"sos" numeric NOT NULL,
	"e_sos" numeric NOT NULL,
	"swiss_rank" bigint DEFAULT '0' NOT NULL,
	"top_cut_rank" bigint,
	"match_points" bigint NOT NULL,
	"corp_deck_id" bigint,
	"runner_deck_id" bigint
);
--> statement-breakpoint
ALTER TABLE "standings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "matches" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"tournament_id" bigint NOT NULL,
	"phase" text DEFAULT '' NOT NULL,
	"round" bigint,
	"table" bigint,
	"corp_id" bigint,
	"runner_id" bigint,
	"result" text
);
--> statement-breakpoint
ALTER TABLE "matches" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "identity_names" (
	"long_id" text PRIMARY KEY NOT NULL,
	"short_id" text
);
--> statement-breakpoint
ALTER TABLE "identity_names" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "standings" ADD CONSTRAINT "standings_tournament_id_fkey" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matches" ADD CONSTRAINT "matches_corp_id_fkey" FOREIGN KEY ("corp_id") REFERENCES "public"."standings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matches" ADD CONSTRAINT "matches_runner_id_fkey" FOREIGN KEY ("runner_id") REFERENCES "public"."standings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matches" ADD CONSTRAINT "matches_tournament_id_fkey" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournaments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE VIEW "public"."standings_mapped" WITH (security_invoker = on) AS (SELECT standings.id, standings.name, standings.created_at, standings.tournament_id, standings.corp_wins, standings.corp_losses, standings.corp_draws, standings.corp_identity, standings.runner_wins, standings.runner_losses, standings.runner_draws, standings.runner_identity, standings.sos, standings.e_sos, standings.swiss_rank, standings.top_cut_rank, standings.match_points, corp_short_ids.short_id AS corp_short_id, runner_short_ids.short_id AS runner_short_id, standings.corp_deck_id, standings.runner_deck_id FROM standings LEFT JOIN identity_names corp_short_ids ON corp_short_ids.long_id = standings.corp_identity LEFT JOIN identity_names runner_short_ids ON runner_short_ids.long_id = standings.runner_identity);--> statement-breakpoint
CREATE VIEW "public"."matches_mapped" WITH (security_invoker = on) AS (WITH mapped_standings AS ( SELECT standings.id, standings.name, standings.created_at, standings.tournament_id, standings.corp_wins, standings.corp_losses, standings.corp_draws, standings.corp_identity, standings.runner_wins, standings.runner_losses, standings.runner_draws, standings.runner_identity, standings.sos, standings.e_sos, standings.swiss_rank, standings.top_cut_rank, standings.match_points, corp_short_ids.short_id AS corp_short_id, runner_short_ids.short_id AS runner_short_id FROM standings LEFT JOIN identity_names corp_short_ids ON corp_short_ids.long_id = standings.corp_identity LEFT JOIN identity_names runner_short_ids ON runner_short_ids.long_id = standings.runner_identity ) SELECT matches.tournament_id, matches.phase, matches.round, matches."table", corp_standings.corp_short_id, runner_standings.runner_short_id, matches.result, matches.runner_id, matches.corp_id FROM matches LEFT JOIN mapped_standings corp_standings ON matches.corp_id = corp_standings.id LEFT JOIN mapped_standings runner_standings ON matches.runner_id = runner_standings.id);--> statement-breakpoint
CREATE VIEW "public"."tournaments_with_player_count" WITH (security_invoker = on) AS (SELECT t.id, t.created_at, t.last_modified_at, t.name, t.url, t.meta, t.date, t.location, t.region, t.format, t.abr_url, t.cardpool, COALESCE(player_counts.player_count, 0::bigint) AS player_count FROM tournaments t LEFT JOIN ( SELECT standings_mapped.tournament_id, count(DISTINCT standings_mapped.name) AS player_count FROM standings_mapped GROUP BY standings_mapped.tournament_id) player_counts ON t.id = player_counts.tournament_id);--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "decklists" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "decklists" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Enable update for authenticated users only" ON "decklists" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "tournaments" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "tournaments" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "cards" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "cards" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Enable update for authenticated users only" ON "cards" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "standings" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "standings" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Enable update for authenticated users only" ON "standings" AS PERMISSIVE FOR UPDATE TO "authenticated";--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "matches" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "matches" AS PERMISSIVE FOR SELECT TO public;--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "identity_names" AS PERMISSIVE FOR SELECT TO public USING (true);
*/