ALTER TABLE "tournaments" ADD COLUMN "catalog_published" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "tournaments" ADD COLUMN "catalog_published_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "standings" ADD COLUMN "source_player_id" text;--> statement-breakpoint

CREATE TABLE "tournament_decklists" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tournament_decklists_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"standing_id" bigint NOT NULL,
	"side" text NOT NULL,
	"source_kind" text DEFAULT 'cobra' NOT NULL,
	"source_url" text,
	"nrdb_url" text,
	"title" text DEFAULT '' NOT NULL,
	"identity" text DEFAULT '' NOT NULL,
	"cards" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"card_count" integer DEFAULT 0 NOT NULL,
	"influence_total" integer,
	"source_hash" text,
	"nrdb_hash" text,
	"comparison_status" text DEFAULT 'unverified' NOT NULL,
	"imported_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_verified_at" timestamp with time zone,
	CONSTRAINT "tournament_decklists_standing_side_key" UNIQUE("standing_id", "side"),
	CONSTRAINT "tournament_decklists_side_check" CHECK ("side" in ('corp', 'runner')),
	CONSTRAINT "tournament_decklists_source_kind_check" CHECK ("source_kind" in ('cobra', 'nrdb', 'manual'))
);--> statement-breakpoint

ALTER TABLE "tournament_decklists" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tournament_decklists" ADD CONSTRAINT "tournament_decklists_standing_id_fkey" FOREIGN KEY ("standing_id") REFERENCES "public"."standings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

CREATE POLICY "Enable update for authenticated users only" ON "tournaments" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Read published tournament decklists" ON "tournament_decklists" AS PERMISSIVE FOR SELECT TO "anon" USING (exists (
	select 1
	from standings s
	join tournaments t on t.id = s.tournament_id
	where s.id = tournament_decklists.standing_id and t.catalog_published = true
));--> statement-breakpoint
CREATE POLICY "Authenticated users can read tournament decklists" ON "tournament_decklists" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can insert tournament decklists" ON "tournament_decklists" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can update tournament decklists" ON "tournament_decklists" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Authenticated users can delete tournament decklists" ON "tournament_decklists" AS PERMISSIVE FOR DELETE TO "authenticated" USING (true);--> statement-breakpoint

GRANT SELECT ON TABLE "tournament_decklists" TO "anon";--> statement-breakpoint
GRANT ALL ON TABLE "tournament_decklists" TO "authenticated";--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE "tournament_decklists_id_seq" TO "authenticated";--> statement-breakpoint

DROP VIEW "public"."tournaments_with_player_count";--> statement-breakpoint
CREATE VIEW "public"."tournaments_with_player_count" WITH (security_invoker = on) AS (
	SELECT t.id, t.created_at, t.last_modified_at, t.name, t.url, t.meta, t.date, t.location, t.region, t.format, t.abr_url, t.cardpool, t.catalog_published, t.catalog_published_at, COALESCE(player_counts.player_count, 0::bigint) AS player_count
	FROM tournaments t
	LEFT JOIN (
		SELECT standings_mapped.tournament_id, count(DISTINCT standings_mapped.name) AS player_count
		FROM standings_mapped
		GROUP BY standings_mapped.tournament_id
	) player_counts ON t.id = player_counts.tournament_id
);--> statement-breakpoint
GRANT SELECT ON TABLE "tournaments_with_player_count" TO "anon", "authenticated";
