/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 *
 * https://steffens.org/nrtm/nrtm-schema.json
 */

export type Round = Game[];

export type Game = CobraGame | AesopsGame;

/**
 * tournament results
 */
export interface Tournament {
  name?: string;
  /**
   * tournament type (gnk, sc etc)
   */
  type?: string;
  /**
   * cards up to this data pack/set were allowed
   */
  allowedSet?: string;
  /**
   * city where the tournament was held
   */
  city?: string;
  /**
   * country where the tournament was held
   */
  country?: string;
  /**
   * date the tournament was held (YYYY-MM-DD)
   */
  date?: string;
  /**
   * app version
   */
  version?: string;
  /**
   * tournament uses pods
   */
  usesPods?: boolean;
  /**
   * for elimination rounds: size of the cut
   */
  cutToTop?: number;
  /**
   * for eliminiation rounds: number of preliminary rounds
   */
  preliminaryRounds?: number;
  /**
   * players in the tournament. this represents the rankings after swiss rounds
   */
  players?: Player[];
  /**
   * players in the elimination rounds. this represents the rankings after elimination rounds
   */
  eliminationPlayers?: EliminationPlayer[];
  /**
   * array of array of game results
   */
  rounds?: Round[];
  [k: string]: unknown;
}
/**
 * a player in this tournament
 */
export interface Player {
  id?: number;
  name?: string;
  rank?: number;
  corpFaction?: string;
  corpIdentity?: string;
  runnerIdentity?: string;
  runnerFaction?: string;
  /**
   * deprecated, use matchPoints instead
   */
  prestige?: number;
  matchPoints?: number;
  strengthOfSchedule?: number;
  extendedStrengthOfSchedule?: number;
  averageScore?: number;
  forfeit?: boolean;
  disqualified?: boolean;
  isBye?: boolean;
  pod?: number;
  [k: string]: unknown;
}
/**
 * a player in the elimination rounds
 */
export interface EliminationPlayer {
  id?: number;
  name?: string;
  /**
   * player's rank after elimination rounds
   */
  rank?: number;
  /**
   * player's rank after swiss rounds
   */
  seed?: number;
  [k: string]: unknown;
}
/**
 * a game's result
 */
export interface CobraGame {
  table?: number;
  player1?: SwissGameResult | EliminationGameResult;
  player2?: SwissGameResult | EliminationGameResult;
  eliminationGame: boolean;
  /**
   * true if this was an intentional draw
   */
  intentionalDraw?: boolean;
  /**
   * game 1 (p1 runner vs p2 corp) win
   */
  game1WonBy?: "ap" | "mill" | "flatline";
  /**
   * game 2 (p1 corp vs p2 runner) win
   */
  game2WonBy?: "ap" | "mill" | "flatline";
  /**
   * elimination game win
   */
  gameWonBy?: "ap" | "mill" | "flatline";
  [k: string]: unknown;
}

export type AesopsGame = AesopsSwissGame | AesopsEliminationGame;

export interface AesopsSwissGame {
  tableNumber?: number;
  corpPlayer?: number;
  runnerPlayer?: number;
  corpIdentity?: string;
  runnerIdentity?: string;
  corpScore?: string;
  runnerScore?: string;
  intentionalDraw?: boolean;
  eliminationGame: false;
}

export interface AesopsEliminationGame {
  tableNumber?: number;
  corpPlayer?: number;
  runnerPlayer?: number;
  winner_id?: number;
  loser_id?: number;
  eliminationGame: true;
}
/**
 * a swiss game's result for one player
 */
export interface SwissGameResult {
  /**
   * refers to player.id
   */
  id: number;
  /**
   * this player's runner score
   */
  runnerScore: null | number;
  /**
   * this player's corp score
   */
  corpScore: null | number;
  [k: string]: unknown;
}
/**
 * an elimination game's result for one player
 */
export interface EliminationGameResult {
  /**
   * refers to player.id
   */
  id: number;
  /**
   * this player's role (corp/runner)
   */
  role: "runner" | "corp";
  /**
   * did this player win?
   */
  winner: boolean;
  [k: string]: unknown;
}
