const ID_MAPPING = {
  "419: Amoral Scammer": "419",
  "A Teia: IP Recovery": "A Teia",
  "Acme Consulting: The Truth You Need": "Acme",
  "AgInfusion: New Miracles for a New World": "AgInfusion",
  "Akiko Nisei: Head Case": "Akiko",
  "Alice Merchant: Clan Agitator": "Alice",
  "Ampère: Cybernetics For Anyone": "Ampère",
  "Arissana Rocha Nahu: Street Artist": "Arissana",
  "Asa Group: Security Through Vigilance": "Asa",
  'Ayla "Bios" Rahim: Simulant Specialist': "Ayla",
  "Az McCaffrey: Mechanical Prodigy": "Az",
  "Azmari EdTech: Shaping the Future": "Azmari",
  "Captain Padma Isbister: Intrepid Explorer": "Padma",
  "Earth Station: SEA Headquarters": "Earth Station",
  "Epiphany Analytica: Nations Undivided": "Epiphany",
  "Esâ Afontov: Eco-Insurrectionist": "Esâ",
  "Freedom Khumalo: Crypto-Anarchist": "Freedom",
  "GameNET: Where Dreams are Real": "GameNET",
  "Haas-Bioroid: Architects of Tomorrow": "AoT",
  "Haas-Bioroid: Precision Design": "PD",
  "Hoshiko Shiro: Untold Protagonist": "Hosh",
  "Hyoubu Institute: Absolute Clarity": "Hyoubu",
  "Issuaq Adaptics: Sustaining Diversity": "Issuaq",
  "Jemison Astronautics: Sacrifice. Audacity. Success.": "Jemison",
  "Jinteki: Personal Evolution": "PE",
  "Jinteki: Restoring Humanity": "RH",
  "Kabonesa Wu: Netspace Thrillseeker": "Kabonesa",
  'Ken "Express" Tenma: Disappeared Clone': "Ken",
  "Lat: Ethical Freelancer": "Lat",
  "Liza Talking Thunder: Prominent Legislator": "Liza",
  "Los: Data Hijacker": "Los",
  "Mercury: Chrome Libertador": "Mercury",
  "MirrorMorph: Endless Iteration": "MirrorMorph",
  "Mti Mwekundu: Life Improved": "Mti",
  'Nathaniel "Gnat" Hall: One-of-a-Kind': "Gnat",
  "NBN: Reality Plus": "NBN",
  "Near-Earth Hub: Broadcast Center": "NEH",
  "Nova Initiumia: Catalyst & Impetus": "Nova",
  "Nuvem SA: Law of the Land": "Nuvem",
  'Nyusha "Sable" Sintashta: Symphonic Prodigy': "Sable",
  "Ob Superheavy Logistics: Extract. Export. Excel.": "Ob",
  "Pravdivost Consulting: Political Solutions": "Pravdivost",
  "Quetzal: Free Spirit": "Quetzal",
  "Reina Roja: Freedom Fighter": "Reina Roja",
  'René "Loup" Arcemont: Party Animal': "Loup",
  'Rene "Loup" Arcemont: Party Animal': "Loup",
  'Rielle "Kit" Peddler: Transhuman': "Kit",
  "Saraswati Mnemonics: Endless Exploration": "Saraswati",
  "Sebastião Souza Pessoa: Activist Organizer": "Seb",
  "Sportsmetal: Go Big or Go Home": "Sportsmetal",
  "SSO Industries: Fueling Innovation": "SSO",
  "Steve Cambridge: Master Grifter": "Steve",
  "Tāo Salonga: Telepresence Magician": "Tāo",
  "The Outfit: Family Owned and Operated": "Outfit",
  "Thule Subsea: Safety Below": "Thule",
  "Thunderbolt Armaments: Peace Through Power": "Thunderbolt",
  "Weyland Consortium: Building a Better World": "BABW",
  "Weyland Consortium: Built to Last": "BtL",
  "Zahya Sadeghi: Versatile Smuggler": "Zahya",
};

export const shortenId = (id?: string) => {
  if (id == null) return "";
  return ID_MAPPING[id as keyof typeof ID_MAPPING] ?? id;
};
